# Generated by Django 5.1.3 on 2024-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='chaivariety',
            name='last_name',
        ),
    ]
